tasks:
  - init: pip install flask transformers torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu sentencepiece requests pillow pyngrok
    command: python main.py
ports:
  - port: 5000
    onOpen: open-preview
